apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        # TODO(zmerlynn): change to gcr.io/google_containers/volume-nfs
        image: jsafrane/nfs-data
        ports:
          - name: nfs
            containerPort: 2049
        securityContext:
          privileged: true
