kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller
  labels:
    component: spark-worker
spec:
  replicas: 3
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
        uses: spark-master
    spec:
      containers:
        - name: spark-worker
          image: gcr.io/google_containers/spark-worker:1.5.1_v1
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: 100m
