apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: job-wq-1
spec:
  selector:
    matchLabels:
      app: job-wq-1
  completions: 8
  parallelism: 2
  template:
    metadata:
      name: job-wq-1
      labels:
        app: job-wq-1
    spec:
      containers:
      - name: c
        image: gcr.io/<project>/job-wq-1
      restartPolicy: OnFailure
