apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    name: openshift
  name: openshift
spec:
  selector:
    matchLabels:
      name: openshift
  replicas: 1
  selector:
    matchLabels:
      name: openshift
  template:
    metadata:
      labels:
        name: openshift
    spec:
      containers:
        - args:
            - start
            - master
            - --config=/config/master-config.yaml
          image: "openshift/origin"
          name: origin
          ports:
            - containerPort: 8443
              name: openshift
          volumeMounts:
            - mountPath: /config
              name: config
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: openshift-config
