apiVersion: v1beta3
kind: Service
metadata:
  labels:
    db: influxdb
  name: rethinkdb-admin
  namespace: rethinkdb
spec:
  containerPort: 8080
  port: 8080
  selector:
    db: rethinkdb
    role: admin
