apiVersion: v1beta3
kind: Pod
metadata:
  labels:
    name: hazelcast
  name: hazelcast
spec:
  containers:
  - image: pires/hazelcast-k8s
    name: hazelcast
    ports:
    - containerPort: 5701
      name: hazelcast
      protocol: TCP
    resources:
      limits:
        cpu: "1"
